const J = JSON.stringify;
const a = [3, 1, 4, 1, 5, 9, 2, 6];
console.log(a.length, a[0], a[a.length - 1]);
console.log(J([...a].sort((x, y) => x - y)));
console.log(J([...a].sort()), J([10, 9, 100, 20].sort()));
console.log(J(a.slice(2, 5)), J(a.slice(-3)), a.indexOf(1), a.includes(9));
console.log(J(a.map((x) => x * 2)), J(a.filter((x) => x > 3)));
console.log(a.reduce((s, x) => s + x, 0), a.reduceRight((s, x) => s + "" + x, ""));
console.log(a.find((x) => x > 4), a.findIndex((x) => x > 4), a.findLast((x) => x < 5));
console.log(a.some((x) => x > 8), a.every((x) => x > 0));
const b = [1, 2, 3];
b.push(4, 5); console.log(J(b), b.pop(), J(b));
b.unshift(0); console.log(J(b), b.shift(), J(b));
console.log(J([1, 2, 3].concat([4, 5], 6)), J([1, 2, 3].reverse()));
const c = [1, 2, 3, 4, 5];
console.log(J(c.splice(1, 2, "a", "b")), J(c));
console.log(J(Array.of(1, 2, 3)), J(Array.from("abc")), J(Array.from([1, 2], (x) => x * 10)));
console.log(Array.isArray([]), Array.isArray({}), new Array(3).length);
console.log(J([1, 2, 3].fill(0)), J([1, 2, 3, 4].fill(9, 1, 3)));
console.log(J([[1, 2], [3, [4]]].flat()), J([1, 2].flatMap((x) => [x, x])));
console.log(a.at(-1), a.at(0), a.join("|"));
