console.log(JSON.stringify({ a: 1, b: [2, 3], c: { d: 4 } }));
console.log(JSON.stringify([1, "two", true, false, null]));
console.log(JSON.stringify({ x: undefined, y: null, z: 1 }));
console.log(JSON.stringify([undefined, function() {}, null]));
console.log(JSON.stringify({ nested: { deep: { value: 42 } } }, null, 2));
console.log(JSON.stringify("string with \"quotes\" and \ backslash"));
console.log(JSON.stringify("tab\there\nnewline"));
console.log(JSON.stringify({ "key with spaces": 1, "special!@#": 2 }));
console.log(JSON.parse('{"a": 1.5e2, "b": -3, "c": true}').a);
console.log(JSON.parse('[1, 2, 3]').length);
console.log(JSON.parse('"\u0041\u0042"'));
console.log(JSON.stringify(NaN), JSON.stringify(Infinity), JSON.stringify(-0));
console.log(JSON.stringify({ a: NaN, b: Infinity }));
console.log(JSON.parse(JSON.stringify({ x: [1, { y: 2 }] })).x[1].y);
console.log(JSON.stringify([]), JSON.stringify({}));
console.log(JSON.stringify({ a: 1 }, null, "\t"));
console.log(JSON.stringify(3.14159), JSON.stringify("hi"), JSON.stringify(true));
console.log(JSON.stringify([1, 2, 3], (k, v) => (typeof v === "number" ? v * 2 : v)));
console.log(JSON.stringify({ a: 1, b: 2, c: 3 }, ["a", "c"]));
console.log(JSON.stringify({ a: 1, b: 2, c: 3 }, (k, v) => (k === "b" ? undefined : v)));
console.log(JSON.stringify({ x: { toJSON() { return "custom"; } }, y: 2 }));
console.log(JSON.stringify({ n: 5, arr: [1, 2], skip: 9 }, ["n", "arr"], 2));
console.log(JSON.stringify({ nested: { a: 1, b: 2 } }, ["nested", "a"]));
