console.log(Math.floor(3.7), Math.ceil(3.2), Math.round(3.5), Math.trunc(3.9), Math.trunc(-3.9));
console.log(Math.abs(-5), Math.sign(-3), Math.sign(0), Math.sign(4));
console.log(Math.max(1, 2, 3), Math.min(4, 5, 6), Math.max(), Math.min());
console.log(Math.pow(2, 10), Math.sqrt(144), Math.cbrt(27));
console.log(Math.floor(Math.PI * 100) / 100, Math.floor(Math.E * 100) / 100);
console.log(Math.round(2.5), Math.round(-2.5), Math.round(0.5), Math.round(-0.5));
console.log(Math.hypot(3, 4), Math.log2(8), Math.log10(1000));
console.log(Math.max(-Infinity, 5), Math.min(Infinity, 5));
console.log(Number.MAX_SAFE_INTEGER, Number.MIN_SAFE_INTEGER, Number.EPSILON > 0);
console.log(Number.MAX_VALUE, Number.MIN_VALUE, Number.POSITIVE_INFINITY, Number.NEGATIVE_INFINITY);
console.log(Number.MAX_VALUE + Number.MAX_VALUE, -Number.MIN_VALUE + Number.MIN_VALUE);
console.log(Object.keys(Number).length, Number.MAX_VALUE + -0 === Number.MAX_VALUE);
console.log((123.456).toFixed(2), (0).toFixed(2), (1.005).toFixed(2), (-1.5).toFixed(0));
console.log(parseInt("FF", 16), parseInt("777", 8), parseInt("101", 2));
console.log(Number("0b101"), Number("0o17"), Number("0xff"), Number("0B11"), Number("0O10"));
console.log((255).toString(16), (255).toString(2), (8).toString(8), (35).toString(36));
console.log(Number.isInteger(5.0), Number.isInteger(5.5), Number.isSafeInteger(2 ** 53));
console.log(Math.floor(-0.5), Math.ceil(-0.5), 7 % 3, -7 % 3, 7 % -3);
console.log(isNaN("x"), isFinite(42), isFinite(Infinity), Number.isNaN(NaN));
console.log(Math.min(...[3, 1, 4, 1, 5]), Math.max(...[9, 2, 6]));
console.log(Math.sinh(1).toFixed(6), Math.cosh(1).toFixed(6), Math.tanh(1).toFixed(6));
console.log(Math.asinh(2).toFixed(6), Math.acosh(2).toFixed(6), Math.atanh(0.5).toFixed(6));
console.log(Math.log1p(0), Math.expm1(0), Math.log1p(1).toFixed(6), Math.expm1(1).toFixed(6));
console.log(Math.fround(1.5), Math.fround(1.1).toFixed(6));
console.log(Math.clz32(1), Math.clz32(0), Math.clz32(1000), Math.imul(3, 4), Math.imul(-5, 6));
console.log(Math.SQRT2.toFixed(6), Math.SQRT1_2.toFixed(6), Math.LN2.toFixed(6), Math.LOG2E.toFixed(6));
