console.log("2024-01-15".match(/(\d+)-(\d+)-(\d+)/).slice(1).join("/"));
console.log("hello world foo".match(/\w+/g).join(","));
console.log("a1b2c3".replace(/(\w)(\d)/g, "$2$1"));
console.log(/^\d{3}-\d{4}$/.test("123-4567"), /^\d{3}-\d{4}$/.test("12-4567"));
console.log("The rain in Spain".replace(/ain/g, "___"));
console.log("camelCaseString".replace(/([A-Z])/g, "_$1").toLowerCase());
console.log("  multiple   spaces  ".replace(/\s+/g, " ").trim());
console.log("a,b;c d".split(/[,; ]/).join("|"));
console.log("price: $42.99".match(/\$(\d+)\.(\d+)/).slice(1).join(" and "));
console.log(/foo(?=bar)/.test("foobar"), /foo(?=bar)/.test("foobaz"));
console.log(/foo(?!bar)/.test("foobaz"), /foo(?!bar)/.test("foobar"));
console.log("Hello World".match(/\b\w/g).join(""));
console.log("aaa".replace(/a/g, "b"), "aaa".replace(/a/, "b"));
console.log("test123test456".match(/\d+/g).map(Number).reduce((a, b) => a + b, 0));
console.log("CamelCase".split(/(?=[A-Z])/).join(" "));
console.log(/(\w)\1/.test("hello"), "hello".match(/(\w)\1/)[0]);
console.log("2023/12/25".replace(/(\d+)\/(\d+)\/(\d+)/, "$3-$2-$1"));
console.log([..."a1b2c3".matchAll ? "yes" : "no"].join(""));
console.log("one two three".replace(/(\w+)\s(\w+)/, "$2 $1"));
