const J = JSON.stringify;
const s = "Hello, World!";
console.log(s.length, s.charAt(0), s.charCodeAt(1), s[7]);
console.log(s.indexOf("o"), s.lastIndexOf("o"), s.indexOf("xyz"));
console.log(s.slice(7), s.slice(-6), s.slice(7, 12), s.slice(-6, -1));
console.log(s.substring(7, 12), s.substring(12, 7));
console.log(s.toUpperCase(), s.toLowerCase());
console.log("|" + "  trim me  ".trim() + "|");
console.log(J("a,b,c".split(",")), J("abc".split("")), J("a-b-c".split("-", 2)));
console.log("ab".repeat(3), "5".padStart(3, "0"), "5".padEnd(3, "-"));
console.log(s.includes("World"), s.startsWith("Hello"), s.endsWith("!"));
console.log("a1b2c3".replace(/\d/g, "#"), "aaa".replace("a", "b"));
console.log("x".concat("y", "z"));
console.log(String.fromCharCode(72, 105), "ABC".charCodeAt(0));
console.log(s.at(0), s.at(-1));
console.log("Hello".replace(/l/g, (m) => m.toUpperCase()));
console.log(`sum=${1 + 2}, nested=${`[${3}]`}`);
console.log("abcABC".replace(/[a-z]/g, "*"));
console.log("The quick brown fox".split(" ").map((w) => w[0].toUpperCase() + w.slice(1)).join(" "));
console.log("|" + "  pad  ".trimStart() + "|" + "  pad  ".trimEnd() + "|");
